@startuml
package Authentication <<subsystem>>

interface "Create new account" as create_acc
interface "Log in" as login
interface "Log out" as logout

Authentication -- create_acc
Authentication -- login
Authentication -- logout

package Post <<subsystem>>

interface "View post" as view_post
interface "Create post" as create_post
interface "Edit post" as edit_post

Post -- view_post
Post -- edit_post
Post -- create_post

package Comment <<subsystem>>

interface "Create comment" as create_comment
interface "View comment" as view_comment
interface "Edit comment" as edit_comment

Comment -- create_comment
Comment -- view_comment
Comment -- edit_comment

package Subreddit <<subsystem>>

interface "Create subreddit" as create_sub
interface "View subreddit" as view_sub
interface "Edit subreddit" as edit_sub

Subreddit -- create_sub
Subreddit -- view_sub
Subreddit -- edit_sub

' Authentication -[hidden]---> Post
' Comment -[hidden]---> Subreddit

package User <<subsystem>>

interface "Follow user" as follow
interface "Block user" as block
interface "Ban user" as ban

User -- follow
User -- block
User -- ban

' Dependencies

login  <.. User
logout <.. User
create_acc <.. User

create_comment <.. User
view_comment <.. User
edit_comment <.. User

@enduml

