@startuml
class AuthenticationController <<control>> {
    // create account()
    // log in ()
}

class IAuthentication <<interface>> {
    createAccount(username: String, password: String)
    verifyPassword(username: String, password: String)
}

class Authentication <<subsystem proxy>> {
    createAccount(username: String, password: String)
    verifyPassword(username: String, password: String)
}

class User <<entity>>

AuthenticationController "0..1" --> "0..1" IAuthentication : do authentication tasks via

IAuthentication <|- Authentication
IAuthentication --> User
Authentication --> User

@enduml
