@startuml

autoactivate on
hide footbox

actor User as user
boundary LoginForm as form
control AuthenticationController as ctl

participant ":AuthenticationSystem \n <<subsystem>>" as subsys

autonumber
user -> form : // submit login form()
form -> ctl : // login()
ctl -> subsys : verifyPassword(username, password)
subsys --> ctl
ctl --> form
deactivate form

@enduml
