@startuml

actor User as user
boundary PostInterface as post_int
control PostController as post_ctl
entity Post as post_ent

user -> post_int : 1: // delete post()
activate post_int
post_int -> post_ctl : 2: // delete post()
activate post_ctl
post_ctl -> post_ent : 3: // delete post()
activate post_ent
deactivate post_ent
deactivate post_ctl
deactivate post_int


@enduml
