@startuml

autoactivate on
hide footbox

actor User as user
boundary CreateAccountForm as form
control AuthenticationController as ctl

participant ": AuthenticationSystem" as subsys <<subsystem proxy>>

autonumber

user -> form : // submit account creation form()
form -> ctl : // create account()
ctl -> ctl : // check constraints()
deactivate ctl
ctl -> subsys : // createAccount(username, password)
subsys --> ctl
ctl --> form
deactivate form

@enduml
