@startuml
skinparam packageStyle rectangle
left to right direction
actor "User" as user
actor "Subreddit Moderator" as mod
actor "Superuser" as su
mod -|> user

rectangle Comment as cmt {
  usecase "Manage comment" as cmt_manage
  usecase "View comment" as cmt_read

  usecase "Vote comment" as cmt_vote
}

user --> cmt_manage
user --> cmt_read

user --> cmt_vote

cmt_read    <-[#blue]- su
cmt_manage  <-[#blue]- su

cmt_manage .> cmt_read : <<extends>>

@enduml
