@startuml
skinparam packageStyle rectangle
left to right direction
actor "User" as user
actor "Subreddit Moderator" as mod
actor "Superuser" as su
mod -|> user

rectangle Subreddit as sub {
  usecase "Create subreddit" as sub_create
  usecase "View subreddit" as sub_read
  usecase "Manage subreddit" as sub_manage
  usecase "Add moderator" as sub_add_mod

  usecase "Join subreddit" as sub_join
  usecase "Leave subreddit" as sub_leave
}

user --> sub_create
user --> sub_leave

mod -[#green]-> sub_manage
mod -[#green]-> sub_add_mod

sub_manage    <-[#blue]- su

sub_create ..> sub_read : <<includes>>
sub_create ..> sub_join : <<includes>>
sub_manage ..> sub_read : <<includes>>

@enduml
