# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # SVG
      - name: Checkout branch svg
        run: git checkout -B svg
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg *.puml
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "Huy-Ngo"
          commit_user_email: "duchuy29092000@gmail.com"
          commit_author: "Huy-Ngo <duchuy29092000@gmail.com>"
          commit_message: "Generate SVG diagrams" 
          branch: svg
      # PNG
      - name: Checkout branch png
        run: git checkout -B png
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng *.puml
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "Huy-Ngo"
          commit_user_email: "duchuy29092000@gmail.com"
          commit_author: "Huy-Ngo <duchuy29092000@gmail.com>"
          commit_message: "Generate PNG diagrams" 
          branch: png
      # XMI
      - name: Checkout branch xmi
        run: git checkout -B xmi
      - name: Generate XMI Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -txmi *.puml
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "Huy-Ngo"
          commit_user_email: "duchuy29092000@gmail.com"
          commit_author: "Huy-Ngo <duchuy29092000@gmail.com>"
          commit_message: "Generate XMI diagrams" 
          branch: xmi

